In [1]:
import pandas as pd
import numpy as np
from warnings import filterwarnings
from swings_detection import detect_swing
filterwarnings('ignore')

In [2]:
data = pd.read_csv('gold_data_5_minutes.csv', index_col='timestamp')

detect_swing(data, 'high')
detect_swing(data, 'low')

swings_highwith window 5 added to dataframe
                      v         vw        o        c        h        l  \
timestamp
2023-06-08 00:00:00  14  1944.5221  1944.36  1944.88  1944.93  1944.00
2023-06-08 00:05:00  13  1945.0800  1944.61  1945.26  1945.41  1944.61
2023-06-08 00:10:00  13  1945.0238  1945.41  1945.29  1945.41  1944.88
2023-06-08 00:15:00  13  1945.3677  1945.00  1945.37  1945.61  1945.00
2023-06-08 00:20:00  13  1945.2877  1945.20  1945.22  1945.35  1945.20

                                 t   n  swings_high
timestamp
2023-06-08 00:00:00  1686182400000  14        False
2023-06-08 00:05:00  1686182700000  13        False
2023-06-08 00:10:00  1686183000000  13        False
2023-06-08 00:15:00  1686183300000  13        False
2023-06-08 00:20:00  1686183600000  13        False
swings_lowwith window 5 added to dataframe
                      v         vw        o        c        h        l  \
timestamp
2023-06-08 00:00:00  14  1944.5221  1944.36  1944.88  1944.93  1944.00
2023-06-08 00:05:00  13  1945.0800  1944.61  1945.26  1945.41  1944.61
2023-06-08 00:10:00  13  1945.0238  1945.41  1945.29  1945.41  1944.88
2023-06-08 00:15:00  13  1945.3677  1945.00  1945.37  1945.61  1945.00
2023-06-08 00:20:00  13  1945.2877  1945.20  1945.22  1945.35  1945.20

                                 t   n  swings_high  swings_low
timestamp
2023-06-08 00:00:00  1686182400000  14        False       False
2023-06-08 00:05:00  1686182700000  13        False       False
2023-06-08 00:10:00  1686183000000  13        False       False
2023-06-08 00:15:00  1686183300000  13        False       False
2023-06-08 00:20:00  1686183600000  13        False       False

In [3]:
print(data['swings_high'].value_counts())
print(data['swings_low'].value_counts())

swings_high
False    47569
True      2773
Name: count, dtype: int64
swings_low
False    47324
True      3018
Name: count, dtype: int64

In [4]:
data['swings_high_price'] = np.where(data['swings_high'], data['h'], np.nan)
data['swings_low_price'] = np.where(data['swings_low'], data['l'], np.nan)
data['swings_high_price'] = data['swings_high_price'].fillna(method='ffill')
data['swings_low_price'] = data['swings_low_price'].fillna(method='ffill')
data.head(20)

,v,vw,o,c,h,l,t,n,swings_high,swings_low,swings_high_price,swings_low_price
timestamp,,,,,,,,,,,,
2023-06-08 00:00:00,14,1944.5221,1944.36,1944.88,1944.93,1944.00,1686182400000,14,False,False,NaN,NaN
2023-06-08 00:05:00,13,1945.0800,1944.61,1945.26,1945.41,1944.61,1686182700000,13,False,False,NaN,NaN
2023-06-08 00:10:00,13,1945.0238,1945.41,1945.29,1945.41,1944.88,1686183000000,13,False,False,NaN,NaN
2023-06-08 00:15:00,13,1945.3677,1945.00,1945.37,1945.61,1945.00,1686183300000,13,False,False,NaN,NaN
2023-06-08 00:20:00,13,1945.2877,1945.20,1945.22,1945.35,1945.20,1686183600000,13,False,False,NaN,NaN
2023-06-08 00:25:00,13,1945.3454,1944.60,1945.32,1945.63,1944.60,1686183900000,13,False,False,NaN,NaN
2023-06-08 00:30:00,13,1945.7239,1945.68,1945.67,1945.89,1945.31,1686184200000,13,False,False,NaN,NaN
2023-06-08 00:35:00,13,1945.5615,1944.90,1945.79,1945.90,1944.90,1686184500000,13,False,False,NaN,NaN
2023-06-08 00:40:00,10,1945.6880,1945.66,1945.78,1945.81,1945.50,1686184800000,10,False,False,NaN,NaN
2023-06-08 00:45:00,13,1945.7831,1945.90,1945.96,1945.99,1945.41,1686185100000,13,False,False,NaN,NaN
2023-06-08 00:50:00,15,1945.8573,1945.10,1945.94,1946.15,1945.10,1686185400000,15,False,False,NaN,NaN
2023-06-08 00:55:00,14,1945.9107,1945.71,1946.12,1946.14,1945.20,1686185700000,14,False,False,NaN,NaN
2023-06-08 01:00:00,13,1946.1215,1946.40,1945.92,1946.47,1945.92,1686186000000,13,False,False,NaN,NaN
2023-06-08 01:05:00,14,1946.1507,1945.60,1946.47,1946.47,1945.60,1686186300000,14,False,False,NaN,NaN
2023-06-08 01:10:00,14,1946.1107,1946.58,1945.69,1946.58,1945.63,1686186600000,14,True,False,1946.58,NaN
2023-06-08 01:15:00,13,1945.3431,1945.39,1945.20,1945.93,1945.12,1686186900000,13,False,False,1946.58,NaN
2023-06-08 01:20:00,13,1945.3515,1945.16,1945.15,1945.69,1945.12,1686187200000,13,False,False,1946.58,NaN
2023-06-08 01:25:00,13,1945.1208,1945.30,1944.86,1945.68,1944.10,1686187500000,13,False,True,1946.58,1944.1
2023-06-08 01:30:00,13,1944.9285,1945.22,1944.62,1945.40,1944.57,1686187800000,13,False,False,1946.58,1944.1
2023-06-08 01:35:00,13,1945.4677,1944.90,1945.57,1945.84,1944.78,1686188100000,13,False,False,1946.58,1944.1

In [8]:
data.dropna(inplace=True)

In [12]:
conditions = [
    data['swings_high_price'].shift(1) < data['c'],
    data['swings_low_price'].shift(1) > data['c']
]

choices = ['Bullish', 'Bearish']

data['structural_break'] = np.select(conditions, choices, default=None)

In [15]:
data['structural_break'].value_counts(dropna=False)

structural_break
None       37717
Bullish     7248
Bearish     5360
Name: count, dtype: int64

,v,vw,o,c,h,l,t,n,swings_high,swings_low,swings_high_price,swings_low_price,Bullish_structure_number,Bearish_structure_number,structure_number
timestamp,,,,,,,,,,,,,,,
2023-06-08 00:00:00,14,1944.5221,1944.36,1944.88,1944.93,1944.00,1686182400000,14,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 00:05:00,13,1945.0800,1944.61,1945.26,1945.41,1944.61,1686182700000,13,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 00:10:00,13,1945.0238,1945.41,1945.29,1945.41,1944.88,1686183000000,13,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 00:15:00,13,1945.3677,1945.00,1945.37,1945.61,1945.00,1686183300000,13,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 00:20:00,13,1945.2877,1945.20,1945.22,1945.35,1945.20,1686183600000,13,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 00:25:00,13,1945.3454,1944.60,1945.32,1945.63,1944.60,1686183900000,13,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 00:30:00,13,1945.7239,1945.68,1945.67,1945.89,1945.31,1686184200000,13,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 00:35:00,13,1945.5615,1944.90,1945.79,1945.90,1944.90,1686184500000,13,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 00:40:00,10,1945.6880,1945.66,1945.78,1945.81,1945.50,1686184800000,10,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 00:45:00,13,1945.7831,1945.90,1945.96,1945.99,1945.41,1686185100000,13,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 00:50:00,15,1945.8573,1945.10,1945.94,1946.15,1945.10,1686185400000,15,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 00:55:00,14,1945.9107,1945.71,1946.12,1946.14,1945.20,1686185700000,14,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 01:00:00,13,1946.1215,1946.40,1945.92,1946.47,1945.92,1686186000000,13,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 01:05:00,14,1946.1507,1945.60,1946.47,1946.47,1945.60,1686186300000,14,False,False,NaN,NaN,0.0,0.0,0.0
2023-06-08 01:10:00,14,1946.1107,1946.58,1945.69,1946.58,1945.63,1686186600000,14,True,False,1946.58,NaN,1.0,0.0,1.0
2023-06-08 01:15:00,13,1945.3431,1945.39,1945.20,1945.93,1945.12,1686186900000,13,False,False,1946.58,NaN,0.0,0.0,0.0
2023-06-08 01:20:00,13,1945.3515,1945.16,1945.15,1945.69,1945.12,1686187200000,13,False,False,1946.58,NaN,0.0,0.0,0.0
2023-06-08 01:25:00,13,1945.1208,1945.30,1944.86,1945.68,1944.10,1686187500000,13,False,True,1946.58,1944.1,0.0,-1.0,-1.0
2023-06-08 01:30:00,13,1944.9285,1945.22,1944.62,1945.40,1944.57,1686187800000,13,False,False,1946.58,1944.1,0.0,0.0,0.0
2023-06-08 01:35:00,13,1945.4677,1944.90,1945.57,1945.84,1944.78,1686188100000,13,False,False,1946.58,1944.1,0.0,0.0,0.0
2023-06-08 01:40:00,14,1945.7893,1945.65,1945.87,1946.09,1945.20,1686188400000,14,False,False,1946.58,1944.1,0.0,0.0,0.0
2023-06-08 01:45:00,13,1945.6492,1945.96,1945.68,1945.96,1945.36,1686188700000,13,False,False,1946.58,1944.1,0.0,0.0,0.0
2023-06-08 01:50:00,13,1945.4431,1945.92,1945.23,1945.92,1945.16,1686189000000,13,False,False,1946.58,1944.1,0.0,0.0,0.0
2023-06-08 01:55:00,14,1945.4350,1945.27,1945.77,1945.77,1944.60,1686189300000,14,False,False,1946.58,1944.1,0.0,0.0,0.0
2023-06-08 02:00:00,13,1945.9515,1945.97,1946.51,1946.51,1945.48,1686189600000,13,False,False,1946.58,1944.1,0.0,0.0,0.0
2023-06-08 02:05:00,13,1946.6208,1946.70,1946.39,1946.89,1946.39,1686189900000,13,True,False,1946.89,1944.1,2.0,0.0,2.0
2023-06-08 02:10:00,13,1945.7408,1945.98,1945.28,1946.48,1945.28,1686190200000,13,False,False,1946.89,1944.1,0.0,0.0,0.0
2023-06-08 02:15:00,13,1945.5231,1945.47,1945.93,1945.93,1945.31,1686190500000,13,False,False,1946.89,1944.1,0.0,0.0,0.0
2023-06-08 02:20:00,13,1946.2839,1946.06,1946.60,1946.78,1945.73,1686190800000,13,False,False,1946.89,1944.1,0.0,0.0,0.0
2023-06-08 02:25:00,12,1946.1850,1946.56,1945.85,1946.70,1945.48,1686191100000,12,False,False,1946.89,1944.1,0.0,0.0,0.0

In [10]:
data = data[['v', 'vw', 'o', 'c', 'h', 'l', 't', 'n', 
             'swings_high', 'swings_low', 
             'swings_high_price', 'swings_low_price', 
             'structure_number']]

In [11]:
data.head()

,v,vw,o,c,h,l,t,n,swings_high,swings_low,swings_high_price,swings_low_price,structure_number
timestamp,,,,,,,,,,,,,
2023-06-08 00:00:00,14,1944.5221,1944.36,1944.88,1944.93,1944.00,1686182400000,14,False,False,NaN,NaN,0.0
2023-06-08 00:05:00,13,1945.0800,1944.61,1945.26,1945.41,1944.61,1686182700000,13,False,False,NaN,NaN,0.0
2023-06-08 00:10:00,13,1945.0238,1945.41,1945.29,1945.41,1944.88,1686183000000,13,False,False,NaN,NaN,0.0
2023-06-08 00:15:00,13,1945.3677,1945.00,1945.37,1945.61,1945.00,1686183300000,13,False,False,NaN,NaN,0.0
2023-06-08 00:20:00,13,1945.2877,1945.20,1945.22,1945.35,1945.20,1686183600000,13,False,False,NaN,NaN,0.0

In [12]:
mask = data['structure_number'] == 0
data.loc[mask, 'structure_number'] = np.nan
data['structure_number'] = data['structure_number'].ffill()

In [13]:
data.head(30)

,v,vw,o,c,h,l,t,n,swings_high,swings_low,swings_high_price,swings_low_price,structure_number
timestamp,,,,,,,,,,,,,
2023-06-08 00:00:00,14,1944.5221,1944.36,1944.88,1944.93,1944.00,1686182400000,14,False,False,NaN,NaN,NaN
2023-06-08 00:05:00,13,1945.0800,1944.61,1945.26,1945.41,1944.61,1686182700000,13,False,False,NaN,NaN,NaN
2023-06-08 00:10:00,13,1945.0238,1945.41,1945.29,1945.41,1944.88,1686183000000,13,False,False,NaN,NaN,NaN
2023-06-08 00:15:00,13,1945.3677,1945.00,1945.37,1945.61,1945.00,1686183300000,13,False,False,NaN,NaN,NaN
2023-06-08 00:20:00,13,1945.2877,1945.20,1945.22,1945.35,1945.20,1686183600000,13,False,False,NaN,NaN,NaN
2023-06-08 00:25:00,13,1945.3454,1944.60,1945.32,1945.63,1944.60,1686183900000,13,False,False,NaN,NaN,NaN
2023-06-08 00:30:00,13,1945.7239,1945.68,1945.67,1945.89,1945.31,1686184200000,13,False,False,NaN,NaN,NaN
2023-06-08 00:35:00,13,1945.5615,1944.90,1945.79,1945.90,1944.90,1686184500000,13,False,False,NaN,NaN,NaN
2023-06-08 00:40:00,10,1945.6880,1945.66,1945.78,1945.81,1945.50,1686184800000,10,False,False,NaN,NaN,NaN
2023-06-08 00:45:00,13,1945.7831,1945.90,1945.96,1945.99,1945.41,1686185100000,13,False,False,NaN,NaN,NaN
2023-06-08 00:50:00,15,1945.8573,1945.10,1945.94,1946.15,1945.10,1686185400000,15,False,False,NaN,NaN,NaN
2023-06-08 00:55:00,14,1945.9107,1945.71,1946.12,1946.14,1945.20,1686185700000,14,False,False,NaN,NaN,NaN
2023-06-08 01:00:00,13,1946.1215,1946.40,1945.92,1946.47,1945.92,1686186000000,13,False,False,NaN,NaN,NaN
2023-06-08 01:05:00,14,1946.1507,1945.60,1946.47,1946.47,1945.60,1686186300000,14,False,False,NaN,NaN,NaN
2023-06-08 01:10:00,14,1946.1107,1946.58,1945.69,1946.58,1945.63,1686186600000,14,True,False,1946.58,NaN,1.0
2023-06-08 01:15:00,13,1945.3431,1945.39,1945.20,1945.93,1945.12,1686186900000,13,False,False,1946.58,NaN,1.0
2023-06-08 01:20:00,13,1945.3515,1945.16,1945.15,1945.69,1945.12,1686187200000,13,False,False,1946.58,NaN,1.0
2023-06-08 01:25:00,13,1945.1208,1945.30,1944.86,1945.68,1944.10,1686187500000,13,False,True,1946.58,1944.1,-1.0
2023-06-08 01:30:00,13,1944.9285,1945.22,1944.62,1945.40,1944.57,1686187800000,13,False,False,1946.58,1944.1,-1.0
2023-06-08 01:35:00,13,1945.4677,1944.90,1945.57,1945.84,1944.78,1686188100000,13,False,False,1946.58,1944.1,-1.0
2023-06-08 01:40:00,14,1945.7893,1945.65,1945.87,1946.09,1945.20,1686188400000,14,False,False,1946.58,1944.1,-1.0
2023-06-08 01:45:00,13,1945.6492,1945.96,1945.68,1945.96,1945.36,1686188700000,13,False,False,1946.58,1944.1,-1.0
2023-06-08 01:50:00,13,1945.4431,1945.92,1945.23,1945.92,1945.16,1686189000000,13,False,False,1946.58,1944.1,-1.0
2023-06-08 01:55:00,14,1945.4350,1945.27,1945.77,1945.77,1944.60,1686189300000,14,False,False,1946.58,1944.1,-1.0
2023-06-08 02:00:00,13,1945.9515,1945.97,1946.51,1946.51,1945.48,1686189600000,13,False,False,1946.58,1944.1,-1.0
2023-06-08 02:05:00,13,1946.6208,1946.70,1946.39,1946.89,1946.39,1686189900000,13,True,False,1946.89,1944.1,2.0
2023-06-08 02:10:00,13,1945.7408,1945.98,1945.28,1946.48,1945.28,1686190200000,13,False,False,1946.89,1944.1,2.0
2023-06-08 02:15:00,13,1945.5231,1945.47,1945.93,1945.93,1945.31,1686190500000,13,False,False,1946.89,1944.1,2.0
2023-06-08 02:20:00,13,1946.2839,1946.06,1946.60,1946.78,1945.73,1686190800000,13,False,False,1946.89,1944.1,2.0
2023-06-08 02:25:00,12,1946.1850,1946.56,1945.85,1946.70,1945.48,1686191100000,12,False,False,1946.89,1944.1,2.0